name: Enny Git Action
run-name: Enny Git action
on: [push]
jobs:
  simple_test_for_now:
    runs-on: ubuntu-latest
      steps:
        - name: Echo hello world
          uses: Action/checkout@v4
        - run: echo "hello everyone"
        - run: pwd
        - run:
      
      - name: Setup Terraform to implement cloud infra
        uses: hashicorp/setup-terraform@v2
         with:
           terraform_version: 1.3.0

      - name: Terraform init
        run: terraform init

        - name: terraform plan
           run: terraform plan

