name: Enny Git Action
run-name: Enny Git action
on: [push]
jobs:
  simple_test_for_now:
    runs-on: ubuntu-latest
      steps:
        - name: Echo hello world
          run: echo "hello everyone"
      
        - name: checkout code from repo
          run: hashicorp/setup-terraform@v2
          with:
           terraform_version: 1.3.0

        - name: Terraform init
          run: terraform init

        - name: terraform plan
           run: terraform plan

