name: Enny Git Action
run-name: Enny Git action
on: [push]

env: 
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  simple_test_for_now:
    runs-on: ubuntu-latest
    steps:
        # - name: Echo hello world
        #   uses: Action/checkout@v4
        
        # - name: greeting
        #   run: echo "hello everyone"

        # - name: welcome message
        #   run: pwd
      
        - name: Setup Terraform to implement cloud infra
          uses: hashicorp/setup-terraform@v2
          with:
           terraform_version: 1.3.0

        - name: Terraform init
          run: terraform init

        - name: Terraform plan
          run:  terraform plan